# Generated by Django 5.2.17 on 2026-08-10 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=300)),
                ('amc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('scheme_code', models.CharField(blank=True, max_length=50, null=True)),
                ('isin_growth', models.CharField(blank=True, max_length=30, null=True)),
                ('isin_dividend', models.CharField(blank=True, max_length=30, null=True)),
                ('plan', models.CharField(blank=True, max_length=30, null=True)),
                ('option', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_fund_schemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheme_name'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('invested_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('average_nav', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('current_nav', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_fund_holdings', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holding', to='mutual_funds.mutualfundscheme')),
            ],
            options={
                'ordering': ['scheme__scheme_name'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SIP', 'SIP'), ('REDEMPTION', 'Redemption'), ('DIVIDEND', 'Dividend')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('units', models.DecimalField(decimal_places=6, max_digits=20)),
                ('nav', models.DecimalField(decimal_places=6, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_fund_transactions', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mutual_funds.mutualfundscheme')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_installment_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sips', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sips', to='mutual_funds.mutualfundscheme')),
            ],
            options={
                'ordering': ['next_installment_date', 'scheme__scheme_name'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nav', models.DecimalField(decimal_places=6, max_digits=20)),
                ('source', models.CharField(default='AMFI', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='mutual_funds.mutualfundscheme')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['scheme', '-date'], name='mutual_fund_scheme__502693_idx'), models.Index(fields=['date'], name='mutual_fund_date_a36dd4_idx')],
                'constraints': [models.UniqueConstraint(fields=('scheme', 'date', 'source'), name='unique_mf_nav')],
            },
        ),
    ]
