# Generated by Django 5.2.17 on 2026-08-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIPInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DUE', 'Due'), ('EXECUTED', 'Executed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='SCHEDULED', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='mutual_funds.sip')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_installment', to='mutual_funds.mutualfundtransaction')),
            ],
            options={
                'ordering': ['scheduled_date'],
                'indexes': [models.Index(fields=['sip', 'scheduled_date'], name='mutual_fund_sip_id_5d5652_idx'), models.Index(fields=['status'], name='mutual_fund_status_7aa0cf_idx')],
                'constraints': [models.UniqueConstraint(fields=('sip', 'scheduled_date'), name='unique_sip_installment')],
            },
        ),
    ]
