# Generated by Django 5.2.17 on 2026-08-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0002_sipinstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfundtransaction',
            name='family_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundtransaction',
            name='portfolio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
