# Generated by Django 5.2.17 on 2026-09-04 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_securitymaster_amc_name_and_more'),
        ('mutual_funds', '0003_mutualfundtransaction_family_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundPortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_date', models.DateField(help_text='The date the disclosed portfolio is as of - not when PWMS fetched/parsed it (see fetched_at).')),
                ('source', models.CharField(choices=[('AMFI', 'AMFI'), ('AMC', 'AMC'), ('OTHER', 'Other')], max_length=10)),
                ('source_reference', models.CharField(blank=True, help_text='File name, URL, or other pointer to the disclosure document this snapshot was parsed from.', max_length=500, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When PWMS ingested this snapshot (not portfolio_date).')),
            ],
            options={
                'ordering': ['-portfolio_date'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundUnderlyingHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_name', models.CharField(help_text='Name as disclosed by the source, kept regardless of resolution.', max_length=300)),
                ('isin', models.CharField(blank=True, help_text='ISIN as disclosed by the source, kept even if unresolved.', max_length=20, null=True)),
                ('asset_type', models.CharField(choices=[('EQUITY', 'Equity'), ('DEBT', 'Debt'), ('GOVERNMENT_SECURITY', 'Government Security'), ('CASH', 'Cash / Cash Equivalent'), ('REIT_INVIT', 'REIT / InvIT'), ('ETF', 'ETF'), ('OTHER', 'Other')], default='OTHER', max_length=25)),
                ('holding_percentage', models.DecimalField(decimal_places=4, help_text="Percent of the scheme's NAV, as disclosed.", max_digits=8)),
                ('holding_value', models.DecimalField(blank=True, decimal_places=2, help_text="Disclosed market/fair value of this position within the scheme, in the scheme's currency. Null when the source doesn't disclose it - never derived/estimated here.", max_digits=20, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Disclosed unit/share count, when the source provides it.', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-holding_percentage'],
            },
        ),
        migrations.AddConstraint(
            model_name='mutualfundscheme',
            constraint=models.UniqueConstraint(fields=('owner', 'scheme_code'), name='unique_mf_scheme_owner_code'),
        ),
        migrations.AddField(
            model_name='mutualfundportfoliosnapshot',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_fund_portfolio_snapshots', to='investments.asset'),
        ),
        migrations.AddField(
            model_name='mutualfundunderlyingholding',
            name='portfolio_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='mutual_funds.mutualfundportfoliosnapshot'),
        ),
        migrations.AddField(
            model_name='mutualfundunderlyingholding',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutual_fund_underlying_holdings', to='investments.securitymaster'),
        ),
        migrations.AddIndex(
            model_name='mutualfundportfoliosnapshot',
            index=models.Index(fields=['asset', '-portfolio_date'], name='mutual_fund_asset_i_f3230c_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundportfoliosnapshot',
            index=models.Index(fields=['portfolio_date'], name='mutual_fund_portfol_e48991_idx'),
        ),
        migrations.AddConstraint(
            model_name='mutualfundportfoliosnapshot',
            constraint=models.UniqueConstraint(fields=('asset', 'portfolio_date', 'source'), name='unique_mf_portfolio_snapshot'),
        ),
        migrations.AddIndex(
            model_name='mutualfundunderlyingholding',
            index=models.Index(fields=['portfolio_snapshot'], name='mutual_fund_portfol_d69075_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundunderlyingholding',
            index=models.Index(fields=['isin'], name='mutual_fund_isin_8d965f_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundunderlyingholding',
            index=models.Index(fields=['security'], name='mutual_fund_securit_3d0550_idx'),
        ),
    ]
