# Generated by Django 5.2.17 on 2026-09-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0004_mutualfundportfoliosnapshot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MutualFundUnderlyingHolding',
        ),
        migrations.DeleteModel(
            name='MutualFundPortfolioSnapshot',
        ),
    ]
