# Generated by Django 5.2.17 on 2026-09-10 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0005_remove_mutualfundunderlyingholding_portfolio_snapshot_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfundholding',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutual_fund_holdings', to='users.familygroup'),
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutual_fund_schemes', to='users.familygroup'),
        ),
        migrations.AddField(
            model_name='mutualfundtransaction',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutual_fund_transactions', to='users.familygroup'),
        ),
        migrations.AddField(
            model_name='sip',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutual_fund_sips', to='users.familygroup'),
        ),
    ]
