# Generated by Django 5.2.17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mutual_funds", "0005_remove_mutualfundunderlyingholding_portfolio_snapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MutualFundUnderlying",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("security_name", models.CharField(max_length=300)),
                (
                    "isin",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "security_key",
                    models.CharField(
                        help_text="Normalized ISIN or security name used for deduplication.",
                        max_length=320,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=24,
                        null=True,
                    ),
                ),
                (
                    "market_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=24,
                        null=True,
                    ),
                ),
                (
                    "percentage_of_nav",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("portfolio_date", models.DateField()),
                ("source", models.CharField(default="AMFI", max_length=20)),
                (
                    "source_reference",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="underlying_holdings",
                        to="mutual_funds.mutualfundscheme",
                    ),
                ),
            ],
            options={
                "ordering": ["-portfolio_date", "-percentage_of_nav", "security_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="mutualfundunderlying",
            constraint=models.UniqueConstraint(
                fields=("scheme", "portfolio_date", "security_key", "source"),
                name="unique_mf_underlying_snapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="mutualfundunderlying",
            index=models.Index(
                fields=["scheme", "-portfolio_date"],
                name="mf_underlying_scheme_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mutualfundunderlying",
            index=models.Index(fields=["isin"], name="mf_underlying_isin_idx"),
        ),
        migrations.AddIndex(
            model_name="mutualfundunderlying",
            index=models.Index(
                fields=["security_key"],
                name="mf_underlying_security_key_idx",
            ),
        ),
    ]
