# Generated by Django 5.2.17 on 2026-09-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0013_family_transaction_order_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='amfimasternav',
            new_name='mutual_fund_scheme__e64ace_idx',
            old_name='mutual_fund_amn_9b4e0a_idx',
        ),
        migrations.RenameIndex(
            model_name='amfimasternav',
            new_name='mutual_fund_date_642887_idx',
            old_name='mutual_fund_amn_6f6a2c_idx',
        ),
        migrations.RenameIndex(
            model_name='amfimasterscheme',
            new_name='mutual_fund_isin_gr_f69879_idx',
            old_name='mutual_fund_amb_7e5c7a_idx',
        ),
        migrations.RenameIndex(
            model_name='amfimasterscheme',
            new_name='mutual_fund_isin_di_d3a821_idx',
            old_name='mutual_fund_amb_6b7d0e_idx',
        ),
    ]
