# Generated by Django 5.2.17 on 2026-08-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('normalized_title', models.CharField(db_index=True, max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('url_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, help_text='Hash of normalized_title + published date bucket. Used to detect the same event reported by multiple sources on the same day.', max_length=64)),
                ('matched_query', models.CharField(blank=True, help_text='The search query that first surfaced this article.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['fingerprint'], name='news_article_fingerprint_idx'), models.Index(fields=['normalized_title'], name='news_article_norm_title_idx'), models.Index(fields=['-published_at'], name='news_article_published_idx')],
            },
        ),
    ]