# Generated by Django 5.2.17 on 2026-08-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioNewsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_type', models.CharField(choices=[('EQUITY', 'Equity'), ('MUTUAL_FUND', 'Mutual Fund')], max_length=20)),
                ('holding_id', models.PositiveIntegerField(help_text='Primary key of the Asset (equity) or MutualFundScheme this alert is about. Not a database FK, since it can point to either model - resolved via holding_type at read time.')),
                ('holding_display_name', models.CharField(help_text="Snapshot of the holding's name at alert creation time, so the alert stays meaningful even if the holding is later renamed or removed.", max_length=300)),
                ('category', models.CharField(choices=[('EARNINGS', 'Earnings'), ('REGULATORY', 'Regulatory'), ('LEGAL', 'Legal'), ('MANAGEMENT', 'Management'), ('M_AND_A', 'M&A'), ('PRODUCT', 'Product'), ('CONTRACT', 'Contract'), ('ORDER', 'Order'), ('CORPORATE_GOVERNANCE', 'Corporate Governance'), ('PROMOTER', 'Promoter'), ('CAPITAL_ALLOCATION', 'Capital Allocation'), ('ANALYST', 'Analyst'), ('INDUSTRY', 'Industry'), ('MACRO', 'Macro'), ('OTHER', 'Other')], max_length=30)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], max_length=20)),
                ('time_horizon', models.CharField(choices=[('short_term', 'Short term'), ('medium_term', 'Medium term'), ('long_term', 'Long term'), ('unspecified', 'Unspecified')], max_length=20)),
                ('relevance_score', models.PositiveSmallIntegerField()),
                ('impact', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('impact_score', models.PositiveSmallIntegerField()),
                ('confidence', models.FloatField()),
                ('portfolio_weight_at_alert', models.FloatField(help_text="Snapshot of the holding's portfolio weight percentage at alert creation time.")),
                ('alert_score', models.FloatField(help_text='Internal alert-priority score (impact_score x portfolio weight x confidence, 0-100). NOT a prediction of future returns.')),
                ('notification_tier', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=20)),
                ('summary', models.TextField()),
                ('portfolio_implication', models.TextField()),
                ('reason', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='portfolio_news.newsarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_news_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-alert_score', '-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='news_alert_user_created_idx'), models.Index(fields=['user', 'is_read'], name='news_alert_user_unread_idx'), models.Index(fields=['user', 'notification_tier'], name='news_alert_user_tier_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'article', 'holding_type', 'holding_id'), name='unique_alert_per_user_article_holding')],
            },
        ),
    ]