# Generated by Django 5.2.17 on 2026-08-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_news', '0002_portfolionewsalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolionewsalert',
            name='relevant',
            field=models.BooleanField(default=True, help_text='Whether Gemini judged this article materially relevant to the holding. Rows with relevant=False are kept (not shown in the user-facing feed) purely so the same article is never re-sent to Gemini for this user/holding on a later monitoring run.'),
        ),
    ]