# Generated by Django 5.2.17 on 2026-08-27 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_news', '0003_portfolionewsalert_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='source_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of distinct publishers that have reported this event. Denormalized alongside source_quality for the same reason.'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_quality',
            field=models.CharField(choices=[('tier_1', 'Primary / Top-Tier'), ('tier_2', 'Reputable'), ('tier_3', 'Unclassified')], default='tier_3', help_text="Best (highest) SourceQualityTier among all NewsArticleSource rows for this event. Denormalized here so alert scoring and feed ordering don't need a join/aggregate on every read; kept in sync by article_store whenever a new source is attached.", max_length=20),
        ),
        migrations.CreateModel(
            name='NewsArticleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('url_hash', models.CharField(db_index=True, max_length=64)),
                ('quality_tier', models.CharField(choices=[('tier_1', 'Primary / Top-Tier'), ('tier_2', 'Reputable'), ('tier_3', 'Unclassified')], default='tier_3', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='portfolio_news.newsarticle')),
            ],
            options={
                'ordering': ['quality_tier', '-first_seen_at'],
                'indexes': [models.Index(fields=['article', 'quality_tier'], name='news_source_article_tier_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'url_hash'), name='unique_source_per_article_url')],
            },
        ),
    ]
