# Generated by Django 5.2.17 on 2026-08-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_news', '0005_backfill_newsarticlesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolionewsalert',
            name='interpretation',
            field=models.TextField(blank=True, help_text='What the event could plausibly mean for the company/sector/portfolio. Explicitly speculative; must not be read as confirmed information.'),
        ),
        migrations.AddField(
            model_name='portfolionewsalert',
            name='key_facts',
            field=models.TextField(blank=True, help_text='What the source explicitly reports - no inference or speculation. Kept separate from interpretation so the feed never presents a guess as a fact.'),
        ),
        migrations.AddField(
            model_name='portfolionewsalert',
            name='materiality',
            field=models.CharField(choices=[('trivial', 'Trivial'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', help_text="How significant the event is on its own terms, independent of this holding's portfolio weight. Distinct from `impact`, which factors into alert scoring.", max_length=20),
        ),
        migrations.AddField(
            model_name='portfolionewsalert',
            name='uncertainty_notes',
            field=models.TextField(blank=True, help_text='What is not known from the source that would matter for a fuller assessment.'),
        ),
    ]
