# Generated by Django 5.2.17 on 2026-10-02 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_news', '0014_portfolionewsmatch_connection_unique'),
        ('users', '0005_sync_tax_rate_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolionewsmatch',
            name='family',
            field=models.ForeignKey(blank=True, help_text="Family scope for this deterministic news match. New matches are created in the user's active family.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_news_matches', to='users.familygroup'),
        ),
    ]
