# Generated by Django 5.2.17 on 2026-10-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_news', '0015_alter_portfolionewsmatch_family'),
        ('portfolio_news', '0015_backfill_news_connection_metadata'),
    ]

    operations = [
    ]
