# Generated by Django 5.2.17 on 2026-10-03 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_news', '0017_remove_obsolete_match_connection_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portfolionewsmatch',
            name='unique_legacy_raw_news_match_per_holding',
        ),
        migrations.RemoveConstraint(
            model_name='portfolionewsmatch',
            name='unique_family_raw_news_match_per_holding',
        ),
        migrations.RemoveIndex(
            model_name='portfolionewsmatch',
            name='news_match_family_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolionewsmatch',
            name='news_match_family_article_idx',
        ),
        migrations.RemoveField(
            model_name='portfolionewsmatch',
            name='family',
        ),
        migrations.AddConstraint(
            model_name='portfolionewsmatch',
            constraint=models.UniqueConstraint(fields=('user', 'article', 'holding_type', 'holding_id'), name='unique_raw_news_match_per_holding'),
        ),
    ]
