# Generated by Django 5.2.17 on 2026-10-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_news', '0020_portfolio_news_query_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='news_article_fp_pub_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolionewsalert',
            name='news_alert_user_rel_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolionewsalert',
            name='news_alert_user_tier_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolionewsmatch',
            name='news_match_user_article_idx',
        ),
    ]
