"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def _env_bool(name, default):
    """Parse a boolean environment variable."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ("true", "1", "yes")


def _env_list(name, default):
    """Parse a comma-separated environment variable into a list."""
    value = os.environ.get(name)
    if value is None:
        return default
    return [item.strip() for item in value.split(",") if item.strip()]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    'django-insecure-duf0^3c*i0zzokar066d50xhzp%0i3j5h40dech-t%%l*=us8k',
)
DEBUG = _env_bool("DEBUG", True)
ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", [])

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'users',
    'investments',
    'market_data',
    'portfolio',
    'analytics',
    'ai',
    'mutual_funds',
    'portfolio_news',
    'watchlist',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASE_ENGINE = os.environ.get('DATABASE_ENGINE', 'sqlite').strip().lower()

if DATABASE_ENGINE in ('postgresql', 'postgres'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'pwms'),
            'USER': os.environ.get('POSTGRES_USER', 'pwms_user'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    SQLITE_DB_PATH = os.environ.get('SQLITE_DB_PATH', '').strip()
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(SQLITE_DB_PATH) if SQLITE_DB_PATH else BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 60,
            },
        }
    }

# SQLITE CONCURRENCY
from django.db.backends.signals import connection_created  # noqa: E402


def _configure_sqlite_pragmas(sender, connection, **kwargs):
    if connection.vendor != 'sqlite':
        return
    cursor = connection.cursor()
    cursor.execute('PRAGMA journal_mode=WAL;')
    cursor.execute('PRAGMA synchronous=NORMAL;')
    cursor.execute('PRAGMA busy_timeout=60000;')
    cursor.close()


connection_created.connect(_configure_sqlite_pragmas)

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
WATCHLIST_BENCHMARK_BSE500_URL = os.getenv("WATCHLIST_BENCHMARK_BSE500_URL", "").strip()
WATCHLIST_BENCHMARK_BSE500_FILE = os.getenv(
    "WATCHLIST_BENCHMARK_BSE500_FILE",
    str(BASE_DIR / "watchlist" / "data" / "bse500_tri.csv"),
)

STATIC_ROOT = BASE_DIR / 'staticfiles'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.SessionAuthentication'],
}

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS', ['http://localhost:4200'])
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS', ['http://localhost:4200'])
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', False)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', False)
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', False)

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Logs are separated by application area so production troubleshooting does not
# require searching through one large application log.  Each file rotates at
# 10 MB and keeps the five most recent backups.
LOG_FORMAT = '%(asctime)s %(levelname)s %(name)s: %(message)s'
LOG_MAX_BYTES = 10 * 1024 * 1024
LOG_BACKUP_COUNT = 5


def _rotating_log_handler(filename, level='INFO'):
    return {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': str(LOGS_DIR / filename),
        'maxBytes': LOG_MAX_BYTES,
        'backupCount': LOG_BACKUP_COUNT,
        'formatter': 'standard',
        'encoding': 'utf-8',
        'level': level,
    }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {'format': LOG_FORMAT},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'errors_file': _rotating_log_handler('errors.log', 'ERROR'),
        'application_file': _rotating_log_handler('application.log'),
        'price_updates_file': _rotating_log_handler('price_updates.log'),
        'transactions_file': _rotating_log_handler('transactions.log'),
        'portfolio_file': _rotating_log_handler('portfolio.log'),
        'mutual_funds_file': _rotating_log_handler('mutual_funds.log'),
        'watchlist_file': _rotating_log_handler('watchlist.log'),
        'news_file': _rotating_log_handler('news.log'),
        'authentication_file': _rotating_log_handler('authentication.log'),
        'imports_file': _rotating_log_handler('imports.log'),
    },
    'root': {
        'handlers': ['console', 'application_file', 'errors_file'],
        'level': 'INFO',
    },
    'loggers': {
        # market_data owns scheduled/market price and NAV refresh logging.
        'market_data': {
            'handlers': ['console', 'price_updates_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Transaction/import operations are kept separate from portfolio
        # calculation logs.
        'portfolio.views': {
            'handlers': ['console', 'transactions_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'portfolio': {
            'handlers': ['console', 'portfolio_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'mutual_funds': {
            'handlers': ['console', 'mutual_funds_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'watchlist': {
            'handlers': ['console', 'watchlist_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'portfolio_news': {
            'handlers': ['console', 'news_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'authentication_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'investments': {
            'handlers': ['console', 'imports_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'application_file', 'errors_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
