"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _env_bool(name, default):
    """
    Env vars are always strings ("True"/"False"/"1"/"0") - this
    turns that into a real bool, defaulting to `default` (a real
    bool, not a string) when the var isn't set at all.
    """

    value = os.environ.get(name)

    if value is None:
        return default

    return value.strip().lower() in ("true", "1", "yes")


def _env_list(name, default):
    """
    Env vars for ALLOWED_HOSTS/CORS_ALLOWED_ORIGINS/etc. are a
    single comma-separated string - this splits it into the list
    Django actually wants, defaulting to `default` (a real list)
    when the var isn't set at all.
    """

    value = os.environ.get(name)

    if value is None:
        return default

    return [
        item.strip()
        for item in value.split(",")
        if item.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
#
# Every deployment-sensitive value below reads from an environment
# variable first, falling back to the exact value this project has
# always used for local dev if that variable isn't set - so nothing
# changes for local dev with no .env file present, and a real
# deployment sets these for real via .env (see .env.example) or the
# host's own environment variables. This is the ONE place these
# values are read - never hardcode a deployment-specific value
# anywhere else.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    'django-insecure-duf0^3c*i0zzokar066d50xhzp%0i3j5h40dech-t%%l*=us8k',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", True)

ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", [])


# Application definition

INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'corsheaders',

    # PWMS applications
    'users',
    'investments',
    'market_data',
    'portfolio',
    'analytics',
    'ai',
    'mutual_funds',
    'portfolio_news',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            # Kept in sync with PRAGMA busy_timeout below - if a
            # concurrent writer (e.g. fetch_amfi_nav, or another
            # user's manual price edit) holds the write lock, other
            # connections wait up to this long before raising
            # "database is locked".
            'timeout': 60,
        },
    }
}


# ==========================================================
# SQLITE CONCURRENCY
# ==========================================================
#
# By default SQLite uses a rollback journal, under which a writer
# blocks every reader for the duration of its transaction (not
# just other writers). PWMS has background threads (the market
# price scheduler and the daily refresh job - see
# market_data.services.daily_refresh_scheduler) that write to the
# database while the app is also serving ordinary requests, so a
# long-running background write (e.g. importing an AMFI NAV file)
# can otherwise block simple GETs like the dashboard or login for
# the whole duration, surfacing as "database is locked" errors
# even with OPTIONS.timeout set above.
#
# WAL (write-ahead log) mode lets readers proceed concurrently
# with a writer - only writer-vs-writer still serializes, and that
# case is what OPTIONS.timeout above already covers by making
# SQLite retry/wait rather than fail immediately. This is a
# process-wide PRAGMA set on every new connection; it does not
# change query results or existing data.
from django.db.backends.signals import connection_created  # noqa: E402


def _configure_sqlite_pragmas(sender, connection, **kwargs):
    if connection.vendor != 'sqlite':
        return

    cursor = connection.cursor()
    cursor.execute('PRAGMA journal_mode=WAL;')
    cursor.execute('PRAGMA synchronous=NORMAL;')
    cursor.execute('PRAGMA busy_timeout=60000;')
    cursor.close()


connection_created.connect(_configure_sqlite_pragmas)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Not set before - fine while DEBUG=True (Django serves static
# files itself in that mode), but collectstatic needs somewhere to
# put files, and Django stops serving static files itself the
# moment DEBUG=False - without this, admin/DRF's own CSS breaks in
# production with no error, just an unstyled page.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# PWMS - Django REST Framework
# ============================================================

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# ============================================================
# PWMS - CORS
# ============================================================

# ============================================================
# PWMS - CORS / CSRF
# ============================================================

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = _env_list(
    "CORS_ALLOWED_ORIGINS",
    ["http://localhost:4200"],
)

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = _env_list(
    "CSRF_TRUSTED_ORIGINS",
    ["http://localhost:4200"],
)

# Not set at all before - fine while everything is plain
# http://localhost, but once this is served over HTTPS these need
# to be on, or cookies get sent over an insecure connection even
# when a secure one is available.
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", False)
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", False)

# ============================================================
# PWMS - Time Zone
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# ============================================================
# PWMS - Logging
# ============================================================
#
# Before this config existed, three different things were all
# called "logging" and behaved completely differently:
#   - print() statements in the schedulers - visible only in
#     whatever terminal happened to be open at the time, gone the
#     moment it's closed
#   - logger.info(...) calls scattered across ~17 files - silently
#     dropped entirely (no handler was ever configured, and INFO is
#     below Python's built-in "no handler found" fallback threshold)
#   - logger.warning/exception(...) - visible on stderr via that
#     same fallback, but still never written anywhere persistent
#
# Every logger.* call in the project (including from print()
# statements converted to logger calls) now goes through ONE
# rotating file handler plus a console handler, so there's one
# real place to look after the fact: logs/pwms.log.

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': (
                '%(asctime)s %(levelname)s '
                '%(name)s: %(message)s'
            ),
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'pwms.log'),
            # 10 MB per file, 5 backups kept (pwms.log.1 ... .5) -
            # bounded total disk usage, no manual rotation needed.
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
    },
    'root': {
        # Every app's logging.getLogger(__name__) call propagates
        # here by default - this is what was missing before, and
        # why logger.info(...) calls were being silently dropped.
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            # Django's own request/server logs still go through
            # the same two handlers, but WARNING+ only - django.
            # request already logs every 4xx/5xx at that level, and
            # routing it through 'root' too would just double it up
            # since propagate defaults to True.
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
