# Generated by Django 5.2.17 on 2026-08-10 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('STOCK', 'Stock'), ('MUTUAL_FUND', 'Mutual Fund'), ('ETF', 'ETF'), ('FIXED_DEPOSIT', 'Fixed Deposit'), ('GOLD', 'Gold'), ('CASH', 'Cash'), ('REAL_ESTATE', 'Real Estate'), ('BOND', 'Bond'), ('CRYPTO', 'Cryptocurrency'), ('OTHER', 'Other')], max_length=30)),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('isin', models.CharField(blank=True, max_length=20, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('average_cost', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('invested_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holding', to='investments.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset__name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('SIP', 'SIP'), ('DIVIDEND', 'Dividend'), ('INTEREST', 'Interest'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BONUS', 'Bonus'), ('SPLIT', 'Split'), ('OTHER', 'Other')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('price_per_unit', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
