# Generated by Django 5.2.17 on 2026-08-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='family_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='portfolio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
