# Generated by Django 5.2.17 on 2026-08-17 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_transaction_family_name_transaction_portfolio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=255)),
                ('portfolio', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('average_cost', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('invested_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('gain', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_positions', to='investments.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['family_name', 'portfolio', 'asset__name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'family_name', 'portfolio', 'asset'), name='unique_portfolio_position')],
            },
        ),
    ]
