# Generated by Django 5.2.17 on 2026-08-17 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_portfolioposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(blank=True, max_length=20, null=True)),
                ('asset_name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('cap_type', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_nav_enabled', models.BooleanField(default=False)),
                ('manual_nav', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_masters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'isin'), name='unique_security_master_owner_isin')],
            },
        ),
    ]
