# Generated by Django 5.2.17 on 2026-08-17 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_securitymaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='security_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='investments.securitymaster'),
        ),
    ]
