# Generated by Django 5.2.17 on 2026-09-10 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_securitymaster_amc_name_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_assets', to='users.familygroup'),
        ),
        migrations.AddField(
            model_name='holding',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_holdings', to='users.familygroup'),
        ),
        migrations.AddField(
            model_name='portfolioposition',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_portfolio_positions', to='users.familygroup'),
        ),
        migrations.AddField(
            model_name='securitymaster',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_security_masters', to='users.familygroup'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to='users.familygroup'),
        ),
    ]
