# Generated by Django 5.2.17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0102_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetunderlyingholding",
            name="isin",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
