# Generated by Django 5.2.17 on 2026-09-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='investmentproduct',
            new_name='watchlist_i_product_2c06ee_idx',
            old_name='watchlist_investment_product__f4f1d5_idx',
        ),
        migrations.RenameIndex(
            model_name='investmentproduct',
            new_name='watchlist_i_product_a7ae9d_idx',
            old_name='watchlist_investment_product__b6f0a3_idx',
        ),
        migrations.RenameIndex(
            model_name='investmentproduct',
            new_name='watchlist_i_isin_267762_idx',
            old_name='watchlist_investment_isin_8f6b9b_idx',
        ),
        migrations.RenameIndex(
            model_name='investmentproduct',
            new_name='watchlist_i_externa_9155e7_idx',
            old_name='watchlist_investment_external_8f1a23_idx',
        ),
        migrations.RenameIndex(
            model_name='performancesnapshot',
            new_name='watchlist_p_product_eb52d7_idx',
            old_name='watchlist_performance_product_date_idx',
        ),
        migrations.RenameIndex(
            model_name='performancesnapshot',
            new_name='watchlist_p_date_45103e_idx',
            old_name='watchlist_performance_date_idx',
        ),
    ]
