# Generated by Django 5.2.17 on 2026-08-27 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('article_analysis', 'Article Analysis'), ('portfolio_chat', 'Portfolio Chat')], max_length=30)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cached_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text="Null for system/background calls not tied to a specific user's request (there currently are none, but this keeps the model correct if that changes).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', '-created_at'], name='gemini_usage_endpoint_idx'), models.Index(fields=['user', '-created_at'], name='gemini_usage_user_idx')],
            },
        ),
    ]
