# Generated by Django 5.2.17 on 2026-08-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('YAHOO_FINANCE', 'Yahoo Finance'), ('AMFI', 'AMFI'), ('MANUAL', 'Manual'), ('OTHER', 'Other')], default='YAHOO_FINANCE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='investments.asset')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['asset', '-date'], name='market_data_asset_i_35a803_idx'), models.Index(fields=['date'], name='market_data_date_b95345_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'date', 'source'), name='unique_asset_market_price')],
            },
        ),
    ]
