# Generated by Django 5.2.17 on 2026-08-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_transaction_advisors_transaction_asset_class_and_more'),
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_price', to='investments.asset')),
            ],
            options={
                'ordering': ['-price_date'],
            },
        ),
    ]
