# Generated by Django 5.2.17 on 2026-08-31 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_manualassetprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketprice',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who manually set this price. Only ever set for source=MANUAL rows; audit trail for manual overrides.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_price_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
