# Generated by Django 5.2.13 on 2026-08-12 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='INR', max_length=3)),
                ('date_format', models.CharField(choices=[('DD MMM YYYY', '12 Aug 2026'), ('DD/MM/YYYY', '12/08/2026'), ('YYYY-MM-DD', '2026-08-12')], default='DD MMM YYYY', max_length=20)),
                ('default_analytics_period', models.PositiveIntegerField(choices=[(30, '30 Days'), (90, '90 Days'), (180, '180 Days'), (365, '1 Year')], default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
