# Generated by Django 5.2.17 on 2026-09-10 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_groups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Who granted this membership (always a System Owner).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('family_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='users.familygroup')),
            ],
            options={
                'ordering': ['family_group__name', 'profile__user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user_id', models.PositiveIntegerField()),
                ('target_username', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('USER_CREATED', 'User created'), ('ROLE_CHANGED', 'Role changed'), ('FAMILY_ADDED', 'Added to family'), ('FAMILY_REMOVED', 'Removed from family'), ('ACTIVATED', 'Account activated'), ('DEACTIVATED', 'Account deactivated'), ('DELETED', 'Account deleted')], max_length=20)),
                ('old_value', models.CharField(blank=True, default='', max_length=255)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='INR', max_length=3)),
                ('date_format', models.CharField(choices=[('DD MMM YYYY', '12 Aug 2026'), ('DD/MM/YYYY', '12/08/2026'), ('YYYY-MM-DD', '2026-08-12')], default='DD MMM YYYY', max_length=20)),
                ('default_analytics_period', models.PositiveIntegerField(choices=[(30, '30 Days'), (90, '90 Days'), (180, '180 Days'), (365, '1 Year')], default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VIEWER', 'Viewer'), ('ADMIN', 'Admin'), ('SUPERUSER', 'Super User'), ('SYSTEM_OWNER', 'System Owner')], default='VIEWER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_family_group', models.ForeignKey(blank=True, help_text="The family currently selected for scoping this user's own data views. Must be one of the user's own family_groups; not itself a membership change.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.familygroup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL)),
                ('family_groups', models.ManyToManyField(blank=True, help_text="Families this user belongs to. Members of the same family can view each other's portfolio data for that family; membership never affects edit permissions, which stay governed by role and actual resource ownership. Only a System Owner may change this.", related_name='members', through='users.FamilyMembership', to='users.familygroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.AddField(
            model_name='familymembership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='users.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='familymembership',
            constraint=models.UniqueConstraint(fields=('profile', 'family_group'), name='unique_profile_family_membership'),
        ),
    ]
