# Generated by Django 5.2.17 on 2026-08-31 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_backfill_user_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_groups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family_group',
            field=models.ForeignKey(blank=True, help_text="Optional shared-visibility group. Members of the same group can view each other's portfolio data; membership never affects edit permissions, which stay governed by role and actual resource ownership.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.familygroup'),
        ),
    ]
