# Generated by Django 5.2.17 on 2026-09-02 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_familygroup_userprofile_family_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_family_group',
            field=models.ForeignKey(blank=True, help_text="The family currently selected for scoping this user's own data views. Must be one of the user's own family_groups; not itself a membership change.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.familygroup'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_members', to='users.familygroup'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'Viewer'), ('ADMIN', 'Admin'), ('SUPERUSER', 'Super User'), ('SYSTEM_OWNER', 'System Owner')], default='VIEWER', max_length=20),
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Who granted this membership (always a System Owner).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('family_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='users.familygroup')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='users.userprofile')),
            ],
            options={
                'ordering': ['family_group__name', 'profile__user__username'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family_groups',
            field=models.ManyToManyField(blank=True, help_text="Families this user belongs to. Members of the same family can view each other's portfolio data for that family; membership never affects edit permissions, which stay governed by role and actual resource ownership. Only a System Owner may change this.", related_name='members', through='users.FamilyMembership', to='users.familygroup'),
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user_id', models.PositiveIntegerField()),
                ('target_username', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('USER_CREATED', 'User created'), ('ROLE_CHANGED', 'Role changed'), ('FAMILY_ADDED', 'Added to family'), ('FAMILY_REMOVED', 'Removed from family'), ('ACTIVATED', 'Account activated'), ('DEACTIVATED', 'Account deactivated'), ('DELETED', 'Account deleted')], max_length=20)),
                ('old_value', models.CharField(blank=True, default='', max_length=255)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='familymembership',
            constraint=models.UniqueConstraint(fields=('profile', 'family_group'), name='unique_profile_family_membership'),
        ),
    ]
