# Generated by Django 5.2.17 on 2026-09-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_copy_legacy_family_group_to_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='family_group',
        ),
    ]
